### PR TITLE
add volunteers

### PR DESCRIPTION
**Pull request by willblake01**
Users need a space to easily find all volunteering related information. Increase volunteer signup rate and eliminate manual work for admins.

-Add Volunteer model
-Add volunteers table
-Update schema version
[finishes #175443512]

### CODE REVIEW

**Comment by willblake01** [comment]
Navbar Volunteer link is commented out but looks like this:

image

**Review by ColinW520 — COMMENTED** [review]
Looks like you’ve got some unrelated changes in the routes file.

what if we changed this PR to JUST introduce the model and the dB table (migration) and nothing else? Nothing to hide or comment out that way

**Comment by runbeyond** [comment]
@ColinW520 How does this look with Will's refactor?

**Comment by runbeyond** [comment]
@willblake01 I think we should move the Volunteer link in between Events and Results

**Review by ColinW520 — APPROVED** [review]

**Pull request merged**
